//! LaTeX fragments the paper `\input`s.
//!
//! The paper contains no typed numbers: every figure it prints is generated
//! here (or by `scripts/regen-results.sh`) and read in from `results/`, so a
//! number in the PDF cannot outlive the code that produced it. Everything in
//! this module emits a *bare* `tabular` — the caption and the surrounding
//! float live in `paper/main.tex`, because those are prose.

use crate::latency::Latency;
use crate::trust::TrustSet;

/// Escapes the one LaTeX special character that can reach a generated cell.
///
/// Deployment names are `[a-z0-9-]`, claim and capability names are
/// snake_case identifiers, and principal ids are DIDs and URNs, so `_` is
/// the whole set. `Deployment::validate` rejects the characters that would
/// break the canonical mechanism grammar, but it does not police LaTeX
/// syntax: if the example set ever grows a name containing `&`, `%`, `#`,
/// `$`, `{`, `}`, `~` or `^`, extend this function rather than discovering
/// it as a build failure in `paper/`. The same caveat, and the same reason,
/// as `tex_escape` in `scripts/regen-results.sh`.
pub fn escape(s: &str) -> String {
    s.replace('_', "\\_")
}

/// A detection latency as the paper writes it. `Never` is `\infty` in the
/// paper's notation, which is what its `\Never` macro expands to; written
/// out rather than emitted as `\Never` so a generated file depends on no
/// macro the paper defines.
pub fn latency(l: &Latency) -> String {
    match l {
        Latency::Never => "$\\infty$".to_string(),
        Latency::Bounded(s) => format!("\\texttt{{{s}s}}"),
    }
}

/// The header comment every generated fragment carries, so that a reader who
/// opens one of these files knows not to edit it and knows what made it.
pub fn header(producer: &str) -> String {
    format!(
        "% Generated by `{producer}` via scripts/regen-results.sh — do not edit.\n\
         % A bare tabular: the caption and float live in paper/main.tex.\n"
    )
}

/// One deployment's residual trust set as a bare `tabular`: the tool's own
/// answer, in the shape of the paper's hand-derived table, so the two can be
/// read against each other.
pub fn trust_set_tabular(t: &TrustSet) -> String {
    let mut out = header("parallax solve --format latex");
    out.push_str(
        "\\begin{tabular}{@{}>{\\raggedright\\arraybackslash}p{4.6cm}\
         >{\\raggedright\\arraybackslash}p{5.3cm}ll@{}}\n\\toprule\n",
    );
    out.push_str("Principal & Capability assumed & Detectable in & Impact \\\\\n\\midrule\n");
    for a in &t.0 {
        out.push_str(&format!(
            "\\texttt{{{}}} & \\texttt{{{}}} & {} & \\textsc{{{}}} \\\\\n",
            escape(&a.principal),
            escape(&a.capability),
            latency(&a.latency),
            format!("{:?}", a.impact).to_lowercase(),
        ));
    }
    out.push_str("\\bottomrule\n\\end{tabular}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::deployment::Deployment;
    use crate::solve::solve;
    use std::path::Path;

    #[test]
    fn underscores_are_escaped_and_nothing_else_is_touched() {
        assert_eq!(
            escape("golden_value_correctness"),
            "golden\\_value\\_correctness"
        );
        assert_eq!(escape("did:web:intel.com"), "did:web:intel.com");
        assert_eq!(escape("sigma1-software"), "sigma1-software");
    }

    #[test]
    fn never_renders_as_infinity_and_a_bound_as_seconds() {
        assert_eq!(latency(&Latency::Never), "$\\infty$");
        assert_eq!(latency(&Latency::Bounded(43_200)), "\\texttt{43200s}");
    }

    /// The Σ₂ table the paper reads: five rows, one of them bounded, every
    /// capability name escaped.
    #[test]
    fn the_tdx_trust_set_renders_five_rows_with_one_bound() {
        let d = Deployment::load(Path::new("examples/sigma2-tdx.toml")).unwrap();
        let t = solve(&d).unwrap();
        let tex = trust_set_tabular(&t);

        assert_eq!(
            tex.matches("\\\\\n").count(),
            6,
            "five body rows plus the header row:\n{tex}"
        );
        assert_eq!(
            tex.matches("$\\infty$").count(),
            4,
            "four undetectable parties:\n{tex}"
        );
        assert_eq!(
            tex.matches("\\texttt{43200s}").count(),
            1,
            "only the collateral authority carries a bound:\n{tex}"
        );
        assert!(tex.contains("\\texttt{golden\\_value\\_correctness}"));
        assert!(
            !tex.contains("{golden_value_correctness}"),
            "unescaped:\n{tex}"
        );
        assert!(tex.starts_with("% Generated by"));
    }
}
