//! LaTeX fragments the paper `\input`s.
//!
//! Every table the paper prints in its results sections is generated here (or
//! by `scripts/regen-results.sh`) and read in from `results/`, so a figure in
//! the PDF cannot outlive the code that produced it. Everything in this
//! module emits a *bare* `tabular` — the caption and the surrounding float
//! live in `paper/main.tex`, because those are prose.

use crate::latency::Latency;
use crate::trust::TrustSet;

/// Renders a string safe to drop into a LaTeX cell, and marks the places the
/// line may break.
///
/// Every character TeX treats specially is escaped, not just `_`. This is not
/// defensive tidiness — an earlier version escaped `_` alone and argued that
/// anything else would surface as a build failure in `paper/`. That argument
/// was false, and falsely reassuring. A principal id of `urn:qe:tdx~v2`
/// rendered as `urn:qe:tdx v2` in the PDF: `~` is an unbreakable space, so
/// the build was clean, no warning was issued, and a published trust manifest
/// silently named a party that does not exist. `%` is worse than
/// hypothetical: `did:web` percent-encodes ports, so
/// `did:web:localhost%3A8080` is spec-conformant input, and `%` starts a
/// comment — everything after it on the line, including the `&` column
/// separators and the `\\` row terminator, would vanish.
///
/// Escaping rather than rejecting is the right trade *here* because these
/// strings are principal ids and capability names out of somebody else's
/// deployment file, and the characters are legitimate in them. Refusing
/// conformant input to keep a table generator simple would be the wrong way
/// round. `scripts/regen-results.sh` makes the opposite choice for the values
/// *it* interpolates, and says why.
///
/// The `\allowbreak` after an escaped `_` is not decoration. Capability names
/// run past thirty characters (`measurement_injection_resistance`), TeX will
/// not hyphenate inside `\texttt`, and a table column narrow enough to hold
/// the rest of the row is narrower than that — so without a stated break
/// opportunity the cell overflows into the margin. This is the paper's own
/// `\ub` macro, applied to the cells the paper does not write by hand. Only
/// `_` gets one: it is the only special character that appears mid-identifier
/// often enough to matter, and a break opportunity after, say, an escaped `$`
/// would break lines in places a reader would not expect.
///
/// One pass over the characters, not a chain of `replace` calls: a chain
/// would rewrite the backslashes an earlier step had just introduced.
pub fn escape(s: &str) -> String {
    let mut out = String::with_capacity(s.len());
    for c in s.chars() {
        match c {
            // `\allowbreak` is a control word, so the trailing space is
            // gobbled by TeX and does not reach the page.
            '_' => out.push_str("\\_\\allowbreak "),
            '&' => out.push_str("\\&"),
            '%' => out.push_str("\\%"),
            '$' => out.push_str("\\$"),
            '#' => out.push_str("\\#"),
            '{' => out.push_str("\\{"),
            '}' => out.push_str("\\}"),
            // These three have no `\`-prefixed form that renders the literal
            // character: `\~` and `\^` are accents that would compose with
            // whatever follows, and `\\` is a row terminator. The `{}` stops
            // the control word from swallowing a following space.
            '~' => out.push_str("\\textasciitilde{}"),
            '^' => out.push_str("\\textasciicircum{}"),
            '\\' => out.push_str("\\textbackslash{}"),
            _ => out.push(c),
        }
    }
    out
}

/// A detection latency as the paper writes it. `Never` is `\infty` in the
/// paper's notation, which is what its `\Never` macro expands to; written
/// out rather than emitted as `\Never` so a generated file depends on no
/// macro the paper defines.
pub fn latency(l: &Latency) -> String {
    match l {
        Latency::Never => "$\\infty$".to_string(),
        Latency::Bounded(s) => format!("\\texttt{{{s}s}}"),
    }
}

/// The header comment every generated fragment carries, so that a reader who
/// opens one of these files knows not to edit it and knows what made it.
pub fn header(producer: &str) -> String {
    format!(
        "% Generated by `{producer}` via scripts/regen-results.sh — do not edit.\n\
         % A bare tabular: the caption and float live in paper/main.tex.\n"
    )
}

/// One deployment's residual trust set as a bare `tabular`: the tool's own
/// answer, in the shape of the paper's hand-derived table, so the two can be
/// read against each other.
pub fn trust_set_tabular(t: &TrustSet) -> String {
    let mut out = header("parallax solve --format latex");
    out.push_str(
        "\\begin{tabular}{@{}>{\\raggedright\\arraybackslash}p{4.6cm}\
         >{\\raggedright\\arraybackslash}p{5.3cm}ll@{}}\n\\toprule\n",
    );
    out.push_str("Principal & Capability assumed & Detectable in & Impact \\\\\n\\midrule\n");
    for a in &t.0 {
        out.push_str(&format!(
            "\\texttt{{{}}} & \\texttt{{{}}} & {} & \\textsc{{{}}} \\\\\n",
            escape(&a.principal),
            escape(&a.capability),
            latency(&a.latency),
            format!("{:?}", a.impact).to_lowercase(),
        ));
    }
    out.push_str("\\bottomrule\n\\end{tabular}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::deployment::Deployment;
    use crate::solve::solve;
    use std::path::Path;

    #[test]
    fn underscores_are_escaped_and_carry_a_break_opportunity() {
        assert_eq!(
            escape("golden_value_correctness"),
            "golden\\_\\allowbreak value\\_\\allowbreak correctness",
            "each underscore is escaped and carries a break opportunity"
        );
        assert_eq!(escape("did:web:intel.com"), "did:web:intel.com");
        assert_eq!(escape("sigma1-software"), "sigma1-software");
    }

    /// Escaping `_` alone was not enough, and the reason it looked like
    /// enough is the point. A principal id of `urn:qe:tdx~v2` built cleanly
    /// and printed `urn:qe:tdx v2` — `~` is an unbreakable space in TeX — so
    /// a published table named a party that does not exist, with no warning
    /// anywhere. `%` would have been worse: it opens a comment, so the rest
    /// of the row, separators and all, would have disappeared.
    #[test]
    fn every_tex_special_character_survives_escaping_as_itself() {
        // A `did:web` with a percent-encoded port is spec-conformant input,
        // not a contrived one.
        assert_eq!(
            escape("did:web:localhost%3A8080"),
            "did:web:localhost\\%3A8080"
        );
        // The one that used to be silently swallowed.
        assert_eq!(escape("urn:qe:tdx~v2"), "urn:qe:tdx\\textasciitilde{}v2");

        for (raw, expected) in [
            ("a&b", "a\\&b"),
            ("a%b", "a\\%b"),
            ("a$b", "a\\$b"),
            ("a#b", "a\\#b"),
            ("a{b", "a\\{b"),
            ("a}b", "a\\}b"),
            ("a~b", "a\\textasciitilde{}b"),
            ("a^b", "a\\textasciicircum{}b"),
            ("a\\b", "a\\textbackslash{}b"),
        ] {
            assert_eq!(escape(raw), expected, "escaping `{raw}`");
        }

        // All of them at once, to catch a single-pass implementation that
        // rewrites the backslashes an earlier substitution introduced.
        assert_eq!(
            escape("~^\\%$#&{}_"),
            "\\textasciitilde{}\\textasciicircum{}\\textbackslash{}\
             \\%\\$\\#\\&\\{\\}\\_\\allowbreak ",
            "a chain of `replace` calls would corrupt this"
        );
    }

    /// The property the exact strings above are there to guarantee: after
    /// escaping, no TeX special character is left standing on its own. A
    /// character that reaches the page unescaped either changes what the
    /// table says (`~`) or destroys the row (`%`).
    #[test]
    fn no_special_character_reaches_a_cell_unescaped() {
        let nasty = "did:web:evil%3A80~a^b\\c{d}e$f#g&h_i";
        let escaped = escape(nasty);
        let mut chars = escaped.chars().peekable();
        while let Some(c) = chars.next() {
            if c == '\\' {
                // Consume the control sequence this backslash introduces:
                // either a single escaped punctuation character or a run of
                // letters naming a command.
                match chars.peek() {
                    Some(x) if x.is_alphabetic() => {
                        while chars.peek().is_some_and(|x| x.is_alphabetic()) {
                            chars.next();
                        }
                    }
                    Some(_) => {
                        chars.next();
                    }
                    None => panic!("trailing backslash in {escaped}"),
                }
                continue;
            }
            assert!(
                !matches!(c, '&' | '%' | '$' | '#' | '_' | '^' | '~'),
                "`{c}` reached the cell unescaped in {escaped}"
            );
        }
    }

    /// The end-to-end shape of the same defect: a nasty principal id inside
    /// a real generated table.
    #[test]
    fn a_principal_id_full_of_specials_renders_faithfully_in_a_table() {
        use crate::latency::Latency;
        use crate::trust::{Assumption, Impact, TrustSet};

        let t = TrustSet::singleton(Assumption {
            principal: "did:web:localhost%3A8080~beta".into(),
            capability: "golden_value_correctness".into(),
            latency: Latency::Never,
            impact: Impact::Soundness,
            mechanism: "m".into(),
        });
        let tex = trust_set_tabular(&t);

        assert!(
            tex.contains("\\texttt{did:web:localhost\\%3A8080\\textasciitilde{}beta}"),
            "the id must arrive intact:\n{tex}"
        );
        // The row must still be a row: one `&`-separated line ending in
        // `\\`. An unescaped `%` would have commented the rest of it away.
        let row = tex
            .lines()
            .find(|l| l.contains("localhost"))
            .expect("the row must exist");
        assert_eq!(
            row.matches(" & ").count(),
            3,
            "four columns, three separators, none swallowed: {row}"
        );
        assert!(row.ends_with("\\\\"), "row terminator survived: {row}");
    }

    #[test]
    fn never_renders_as_infinity_and_a_bound_as_seconds() {
        assert_eq!(latency(&Latency::Never), "$\\infty$");
        assert_eq!(latency(&Latency::Bounded(43_200)), "\\texttt{43200s}");
    }

    /// The Σ₂ table the paper reads: five rows, one of them bounded, every
    /// capability name escaped.
    #[test]
    fn the_tdx_trust_set_renders_five_rows_with_one_bound() {
        let d = Deployment::load(Path::new("examples/sigma2-tdx.toml")).unwrap();
        let t = solve(&d).unwrap();
        let tex = trust_set_tabular(&t);

        assert_eq!(
            tex.matches("\\\\\n").count(),
            6,
            "five body rows plus the header row:\n{tex}"
        );
        assert_eq!(
            tex.matches("$\\infty$").count(),
            4,
            "four undetectable parties:\n{tex}"
        );
        assert_eq!(
            tex.matches("\\texttt{43200s}").count(),
            1,
            "only the collateral authority carries a bound:\n{tex}"
        );
        assert!(tex.contains("\\texttt{golden\\_\\allowbreak value\\_\\allowbreak correctness}"));
        assert!(
            !tex.contains("{golden_value_correctness}"),
            "unescaped:\n{tex}"
        );
        assert!(tex.starts_with("% Generated by"));
    }
}
